### PR TITLE
Add enrollment mutation

### LINKED ISSUE #7: Enrollment data can be mutated
**Story:** As an API consumer, I want to be able to mutate an enrollment to change the entry and/or exit date.

**Acceptance criteria:**

* I should be able to make a GraphQL mutation like the following:

```
{
  updateEnrollment(id: 1) {
    id
    entry
    exit
  }
}
```

**Related:** #8

### PR DESCRIPTION
**Pull request by cailyncodes**
I have a question about the process for clearing an exit date (i.e. setting it to null). I'm not sure if this is a supported use case but needed to check in. /cc @cmgiven 

Should resolve #7

### CODE REVIEW

**Comment by cmgiven** [comment]
I think clearing the exit date should be supported. But that's just a guess for now.

**Comment by cailyncodes** [comment]
Are we comfortable requiring the exit parameter unless we are clearing exit date? That is, an exit date is cleared if and only if no exit parameter is supplied.

**Comment by cmgiven** [comment]
I guess that feels a little unintuitive? I think I would expect:

No argument supplied: It doesn't change anything.
Argument supplied with a null value: It clears the date.

**Comment by cailyncodes** [comment]
Yeah ~~I was concerned that you'd say that~~ I think that's a better flow -- I just need to figure out how to allow either a string representing a date or a string representing null to coexist as an argument value.

**Comment by cmgiven** [comment]
Lol. :+1:

**Pull request merged**
