### PR TITLE
Change the name to ECE Reporter

### PR DESCRIPTION
**Pull request by cmgiven**
We have a name!

### CODE REVIEW

**Comment by jlhogan** [comment]
Happy to merge this, but there are definitely other `hedwig`s in the repo, for instance `HedwigRepository` base class etc etc.

**Comment by cmgiven** [comment]
Yeah, figured it wasn't necessary to excise the codename everywhere. Maybe we want to come back to that later?

**Comment by cailyncodes** [comment]
Do we want to change the repo name on Github, too?

**Comment by cmgiven** [comment]
Ooh, good call.

**Comment by cmgiven** [comment]
But actually, let's hold off on that until we check with @speedcm that that won't break anything.

**Pull request merged**
